import { ScanReport } from "./types";

export const STUB_REPORT: ScanReport = {
  scan_id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  timestamp: new Date().toISOString(),
  target: "http://localhost:5000",
  status: "complete",
  summary: {
    total_vulnerabilities: 5,
    critical: 2,
    high: 1,
    medium: 1,
    low: 1,
    info: 0,
  },
  vulnerabilities: [
    {
      id: "vuln-1",
      type: "SQL_INJECTION",
      severity: "critical",
      title: "SQL Injection in /api/login",
      description:
        "The 'username' parameter is interpolated directly into a raw SQL query without sanitisation. An attacker can bypass authentication or dump the entire database.",
      endpoint: "/api/login",
      method: "POST",
      payload: "' OR '1'='1' --",
      evidence: "HTTP 200 returned with admin token when crafted payload applied. Full user table visible in response body.",
      remediation: "Replace raw string interpolation with parameterised queries or a battle-tested ORM.",
      cvss_score: 9.8,
      agent: "SQLiAgent",
    },
    {
      id: "vuln-2",
      type: "AUTH_BYPASS",
      severity: "critical",
      title: "JWT Secret Hardcoded in Source",
      description:
        "The application signs JWTs with a hardcoded secret key ('supersecret'). Any attacker with source access can forge arbitrary tokens.",
      endpoint: "/api/login",
      method: "POST",
      payload: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.<forged>",
      evidence: "Forged admin JWT accepted with HTTP 200 and full admin privileges.",
      remediation: "Rotate to a cryptographically random 256-bit secret stored in an environment variable. Never commit secrets.",
      cvss_score: 9.1,
      agent: "AuthAgent",
    },
    {
      id: "vuln-3",
      type: "IDOR",
      severity: "high",
      title: "IDOR on /api/users/:id",
      description:
        "Endpoint returns any user record without verifying that the requesting user is the record owner. Allows horizontal privilege escalation.",
      endpoint: "/api/users/2",
      method: "GET",
      payload: null,
      evidence: "User authenticated as ID 1 retrieved full PII for user ID 2 with HTTP 200.",
      remediation: "Add server-side ownership validation on every user-scoped resource before returning data.",
      cvss_score: 7.5,
      agent: "AuthAgent",
    },
    {
      id: "vuln-4",
      type: "XSS",
      severity: "medium",
      title: "Reflected XSS in /api/search",
      description:
        "The ?q= query parameter is echoed unsanitised directly into the HTML response body, enabling script injection in all major browsers.",
      endpoint: "/api/search",
      method: "GET",
      payload: "<img src=x onerror=\"alert(document.cookie)\">",
      evidence: "Payload reflected verbatim; script executed and exfiltrated session cookie in test environment.",
      remediation: "HTML-encode all user-controlled output. Implement a strict Content-Security-Policy header.",
      cvss_score: 6.1,
      agent: "XSSAgent",
    },
    {
      id: "vuln-5",
      type: "PATH_TRAVERSAL",
      severity: "low",
      title: "Partial Path Traversal on /api/characters",
      description:
        "The 'name' parameter is used as a filename without normalisation. Partial path traversal is possible but mitigated by chroot.",
      endpoint: "/api/characters",
      method: "GET",
      payload: "../etc/passwd",
      evidence: "Server returned 500 with stack trace leaking internal directory structure.",
      remediation: "Normalise and validate all file paths. Never expose stack traces in production.",
      cvss_score: 3.1,
      agent: "ReconAgent",
    },
  ],
  agent_logs: [
    {
      agent: "ReconAgent",
      timestamp: new Date(Date.now() - 60000).toISOString(),
      action: "Endpoint enumeration",
      result: "Discovered 5 endpoints: /api/login, /api/users/:id, /api/search, /api/characters, /api/logout",
    },
    {
      agent: "SQLiAgent",
      timestamp: new Date(Date.now() - 52000).toISOString(),
      action: "SQL injection probe on /api/login",
      result: "VULNERABLE — payload \"' OR '1'='1' --\" returned HTTP 200 with admin credentials.",
    },
    {
      agent: "AuthAgent",
      timestamp: new Date(Date.now() - 45000).toISOString(),
      action: "JWT secret brute-force",
      result: "VULNERABLE — secret 'supersecret' confirmed via offline brute-force. Forged token accepted.",
    },
    {
      agent: "AuthAgent",
      timestamp: new Date(Date.now() - 38000).toISOString(),
      action: "IDOR probe on /api/users/2",
      result: "VULNERABLE — authenticated as user 1, accessed user 2's full PII without error.",
    },
    {
      agent: "XSSAgent",
      timestamp: new Date(Date.now() - 28000).toISOString(),
      action: "Reflected XSS probe on /api/search",
      result: "VULNERABLE — payload reflected unescaped in HTML body. Script execution confirmed.",
    },
    {
      agent: "ReconAgent",
      timestamp: new Date(Date.now() - 15000).toISOString(),
      action: "Path traversal probe on /api/characters",
      result: "PARTIAL — traversal attempted; server returned 500 with stack trace. Chroot prevents full exploitation.",
    },
    {
      agent: "SynthAgent",
      timestamp: new Date(Date.now() - 5000).toISOString(),
      action: "Report synthesis",
      result: "5 vulnerabilities found. 2 Critical, 1 High, 1 Medium, 1 Low. Report generated.",
    },
  ],
};
